# import time
#
# from selenium import webdriver
# from src3.pages.firstpage import FirstPage
# from src3.pages.secondpage import SecondPage
# from src3.pages.productspage import ProductsPage
# from src3.pages.cartpage import CartPage
#
#
# def test_1():
#     driver = webdriver.Chrome('E:/PycharmProjects/chromedriver.exe')
#     driver.implicitly_wait(10)
#     driver.get("https://tazz.ro/")
#     driver.maximize_window()
#     time.sleep(1)
#
#     firstpage = FirstPage(driver)
#     secondpage = SecondPage(driver)
#     productspage = ProductsPage(driver)
#     cartpage = CartPage(driver)
#
#     firstpage.cookies_select()
#     time.sleep(1)
#     driver.execute_script("window.scrollTo(0, 800)")
#     time.sleep(1)
#     firstpage.iasi_select()
#     time.sleep(1)
#     firstpage.adresa_select()
#     time.sleep(1)
#     firstpage.adressadd_select()
#     time.sleep(1)
#     firstpage.locatie_text()
#     time.sleep(1)
#     firstpage.locatie_select()
#     time.sleep(1)
#     firstpage.confirm_select()
#     time.sleep(1)
#     firstpage.detalii_text()
#     time.sleep(1.5)
#     firstpage.acasa_select()
#     time.sleep(1)
#     firstpage.save_select()
#     time.sleep(1)
#
#     secondpage.bauturitutun_select()
#     time.sleep(1)
#     secondpage.hora_select()
#     time.sleep(1)
#     driver.execute_script("window.scrollTo(0, 250)")
#     time.sleep(1)
#     secondpage.tarie_select()
#     time.sleep(1)
#
#     productspage.bardar_select()
#     time.sleep(1)
#     productspage.plus_select()
#     time.sleep(0.5)
#     productspage.plus_select()
#     time.sleep(1)
#     productspage.adauga_select()
#     time.sleep(1)
#     productspage.backhora_select()
#     time.sleep(1)
#     driver.execute_script("window.scrollTo(0, 250)")
#     time.sleep(1)
#     productspage.vin_select()
#     time.sleep(1)
#     productspage.taraboste_select()
#     time.sleep(1)
#     productspage.plus2_select()
#     time.sleep(0.5)
#     productspage.plus2_select()
#     time.sleep(0.5)
#     productspage.adauga2_select()
#     time.sleep(1)
#     driver.execute_script("window.scrollTo(0, 500)")
#     time.sleep(1)
#     productspage.novak_select()
#     time.sleep(1)
#     productspage.plus3_select()
#     time.sleep(1)
#     productspage.adauga3_select()
#     time.sleep(1)
#
#     cartpage.cart_select()
#     time.sleep(1)
#     driver.execute_script("window.scrollTo(0, 450)")
#     time.sleep(3)
#     cartpage.adauga_select()
#     time.sleep(3)
#     cartpage.mesaj_text()
#     time.sleep(4)
